---
- hosts: localhost
  gather_facts: no
  vars:
    list1: ['Template 1','Template 2','Template 3']
  tasks:
  - name: Ansible template loop example.
    template:
      src: template1.j2
      dest: /tmp/templatej2.txt
      mode: 0777
